apiVersion: v1
kind: Secret
metadata:
  name: django-secrets
type: Opaque
data:
  # POSTGRES_DB: ZGI=
  # POSTGRES_USER: YWRtaW4=
  # POSTGRES_PASSWORD: MTIz
  SECRET_KEY: cmVwbGFjZV9tZQ==
  DEBUG: ZmFsc2U=
  DATABASE_URL: cG9zdGdyZXM6Ly9lZHUtc2lsbHktbGFtYXJyOkBKclRfdkhIUUpfTTQxeDVAcmMxYi1xaXR3a3cwa3dlZm5oYXN0Lm1kYi55YW5kZXhjbG91ZC5uZXQ6NjQzMi9lZHUtc2lsbHktbGFtYXJyP3NzbG1vZGU9cmVxdWlyZQ==
  ALLOWED_HOSTS: QUxMT1dFRF9IT1NUUz0xMjcuMC4wLjEsbG9jYWxob3N0LGVkdS1zaWxseS1sYW1hcnIuc2lyaXVzLWs4cy5kdm1uLm9yZw==