apiVersion: batch/v1
kind: Job
metadata:
  name: migrate
  labels:
    app: django-app
spec:
  template:
    spec:
      volumes:
        - name: secret-volume
          secret:
            secretName: pg-root-cert
      containers:
        - name: migrate
          image: malykh/dvmn-k8s@sha256:3091573ec669e881aa7c0b778d6eb01b35cc201f88ac7a5fb64034684c355ac1
          imagePullPolicy: IfNotPresent
          command: [ "python", "manage.py", "migrate", "--noinput" ]
          volumeMounts:
            - name: secret-volume
              readOnly: true
              mountPath: "/root/.postgresql"
          envFrom:
            - secretRef:
                name: django-secrets 
      restartPolicy: OnFailure
  backoffLimit: 3