apiVersion: v1
kind: Pod
metadata:
  name: test_secret
spec:
  volumes:
  - name: secret-volume
    secret:
      secretName: psql-ssl
  containers:
    - name: ubuntu-psql
      image: ubuntu
      command: ["/bin/sh"]
      args:
        - "-c"
        - |
          apt-get update &&
          apt-get install -y postgresql-client &&
          mkdir -p /root/.postgresql &&
          sleep 3600
      volumeMounts:
        - name: secret-volume
          readOnly: true
          mountPath: "/root/.postgresql"